// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Teste2.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20250817231811_newCepModelMigration")]
    partial class newCepModelMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CnaeSecundario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Codigo")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao");

                    b.Property<string>("EmpresaCnpj")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("EmpresaCnpj");

                    b.ToTable("CnaeSecundario");

                    b.HasAnnotation("Relational:JsonPropertyName", "cnaes_secundarios");
                });

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cnpj");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bairro");

                    b.Property<decimal>("CapitalSocial")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "capital_social");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cep");

                    b.Property<long>("CnaeFiscal")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "cnae_fiscal");

                    b.Property<string>("CnaeFiscalDescricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cnae_fiscal_descricao");

                    b.Property<int>("CodigoMunicipio")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_municipio");

                    b.Property<int>("CodigoMunicipioIbge")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_municipio_ibge");

                    b.Property<int>("CodigoNaturezaJuridica")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_natureza_juridica");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_pais");

                    b.Property<int>("CodigoPorte")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_porte");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "complemento");

                    b.Property<string>("DataExclusaoDoMei")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_exclusao_do_mei");

                    b.Property<string>("DataExclusaoDoSimples")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_exclusao_do_simples");

                    b.Property<string>("DataInicioAtividade")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_inicio_atividade");

                    b.Property<string>("DataOpcaoPeloMei")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_opcao_pelo_mei");

                    b.Property<string>("DataOpcaoPeloSimples")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_opcao_pelo_simples");

                    b.Property<string>("DataSituacaoCadastral")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_situacao_cadastral");

                    b.Property<string>("DataSituacaoEspecial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_situacao_especial");

                    b.Property<string>("DddFax")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ddd_fax");

                    b.Property<string>("DddTelefone1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ddd_telefone_1");

                    b.Property<string>("DddTelefone2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ddd_telefone_2");

                    b.Property<string>("DescricaoIdentificadorMatrizFilial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao_identificador_matriz_filial");

                    b.Property<string>("DescricaoMotivoSituacaoCadastral")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao_motivo_situacao_cadastral");

                    b.Property<string>("DescricaoPorte")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao_porte");

                    b.Property<string>("DescricaoSituacaoCadastral")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao_situacao_cadastral");

                    b.Property<string>("DescricaoTipoDeLogradouro")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao_tipo_de_logradouro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("EnteFederativoResponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ente_federativo_responsavel");

                    b.Property<int>("IdentificadorMatrizFilial")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "identificador_matriz_filial");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "logradouro");

                    b.Property<int>("MotivoSituacaoCadastral")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "motivo_situacao_cadastral");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "municipio");

                    b.Property<string>("NaturezaJuridica")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "natureza_juridica");

                    b.Property<string>("NomeCidadeNoExterior")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nome_cidade_no_exterior");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nome_fantasia");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "numero");

                    b.Property<bool?>("OpcaoPeloMei")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "opcao_pelo_mei");

                    b.Property<bool>("OpcaoPeloSimples")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "opcao_pelo_simples");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pais");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "porte");

                    b.Property<int>("QualificacaoDoResponsavel")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "qualificacao_do_responsavel");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "razao_social");

                    b.Property<int>("SituacaoCadastral")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "situacao_cadastral");

                    b.Property<string>("SituacaoEspecial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "situacao_especial");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "uf");

                    b.HasKey("Cnpj");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Qsa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CnpjCpfDoSocio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cnpj_cpf_do_socio");

                    b.Property<int>("CodigoFaixaEtaria")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_faixa_etaria");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_pais");

                    b.Property<int>("CodigoQualificacaoRepresentanteLegal")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_qualificacao_representante_legal");

                    b.Property<int>("CodigoQualificacaoSocio")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo_qualificacao_socio");

                    b.Property<string>("CpfRepresentanteLegal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cpf_representante_legal");

                    b.Property<string>("DataEntradaSociedade")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "data_entrada_sociedade");

                    b.Property<string>("EmpresaCnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaixaEtaria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "faixa_etaria");

                    b.Property<int>("IdentificadorDeSocio")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "identificador_de_socio");

                    b.Property<string>("NomeRepresentanteLegal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nome_representante_legal");

                    b.Property<string>("NomeSocio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nome_socio");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pais");

                    b.Property<string>("QualificacaoRepresentanteLegal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "qualificacao_representante_legal");

                    b.Property<string>("QualificacaoSocio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "qualificacao_socio");

                    b.HasKey("id");

                    b.HasIndex("EmpresaCnpj");

                    b.ToTable("Qsa");

                    b.HasAnnotation("Relational:JsonPropertyName", "qsa");
                });

            modelBuilder.Entity("RegimeTributario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "ano");

                    b.Property<string>("CnpjDaScp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "cnpj_da_scp");

                    b.Property<string>("EmpresaCnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaDeTributacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "forma_de_tributacao");

                    b.Property<int>("QuantidadeDeEscrituracoes")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "quantidade_de_escrituracoes");

                    b.HasKey("id");

                    b.HasIndex("EmpresaCnpj");

                    b.ToTable("RegimeTributario");

                    b.HasAnnotation("Relational:JsonPropertyName", "regime_tributario");
                });

            modelBuilder.Entity("CnaeSecundario", b =>
                {
                    b.HasOne("Empresa", null)
                        .WithMany("CnaesSecundarios")
                        .HasForeignKey("EmpresaCnpj");
                });

            modelBuilder.Entity("Qsa", b =>
                {
                    b.HasOne("Empresa", null)
                        .WithMany("Qsa")
                        .HasForeignKey("EmpresaCnpj");
                });

            modelBuilder.Entity("RegimeTributario", b =>
                {
                    b.HasOne("Empresa", null)
                        .WithMany("RegimeTributario")
                        .HasForeignKey("EmpresaCnpj");
                });

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Navigation("CnaesSecundarios");

                    b.Navigation("Qsa");

                    b.Navigation("RegimeTributario");
                });
#pragma warning restore 612, 618
        }
    }
}
